version: '3.1'
services:
  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - environment.env
    volumes:
      - .\Volumes\MySQL:/var/lib/mysql
    ports:
      - 3306:3306
  node:
    image: docker.bugsbunnies.de/sep-backend:0.1
    restart: always
    env_file:
      - environment.env
    depends_on: 
      - mysql
    ports: 
      - "3000:3000"  
